apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: avatars-pvc
  namespace: misago
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 1Gi
  volumeName: misago-avatars-pv
