apiVersion: v1
kind: PersistentVolume
metadata:
  name: misago-backups-pv
  labels:
    app: misago
spec:
  storageClassName: ""
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 192.168.1.203
    path: "/data/share/misago/backups-pv"
  mountOptions:
    - nfsvers=4.2
