apiVersion: v1
kind: Service
metadata:
  name: nginx-svc
  namespace: misago
  labels:
    app: misago
spec:
  type: NodePort
  selector:
    app: misago
    type: proxy
  ports:
    - port: 80
      targetPort: 80
      nodePort: 31080
