apiVersion: v1
kind: Service
metadata:
  name: redis-svc
  namespace: misago
spec:
  type: NodePort
  selector:
    app: misago
    type: redis
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
      nodePort: 31379
