apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: static-pvc
  namespace: misago
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 100Mi
  volumeName: misago-static-pv
